columns:
  town: ["town"]
  page: ["page"]
  url: ["url"]
  property_type: ["property_type"]
  price: ["price"]
  address: ["address"]
  postal_code: ["postal_code"]
  bedrooms: ["bedrooms"]
  bedroom1_surface: ["bedroom1_surface"]
  bedroom2_surface: ["bedroom2_surface"]
  bathrooms: ["bathrooms"]
  toilets: ["toilets"]
  surface: ["surface_livable"]
  terrace: ["terrace"]
  terrace_surface: ["terrace_surface"]
  terrace_orientation: ["terrace_orientation"]
  floor: ["floor"]
  year_built: ["year_built"]
  condition: ["condition"]
  kitchen_equipment: ["kitchen_equipment"]
  cellar: ["cellar"]
  glazing_type: ["glazing_type"]
  elevator: ["elevator"]
  entry_phone: ["entry_phone"]
  epc_score: ["epc_score"]
  epc_total: ["epc_total"]
  epc_valid_until: ["epc_valid_until"]
